config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  devise_scope :user do
    get '/admin', to: 'admin/sessions#new'
    post '/admin', to: 'admin/sessions#create'
  end

  resources :categories, only: [:index, :show] do
    get '/:id', to: 'videos#show'
  end

  resources :videos, only: :update

  get '/home-items', to: 'home#home_items'

  namespace :admin do
    resources :dashboard, only: :index
    resources :categories, only: [:create, :show, :destroy]
    resources :artists, only: [:create, :show, :destroy]
    resources :playlists, only: [:create, :show, :destroy]
    resources :videos, only: [:create, :destroy]
  end

  root to: "home#index"
end

app/models/artist.rb
class Artist < ActiveRecord::Base

  validates :name, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :videos, dependent: :destroy

  has_many :subcategories, class_name: 'Category', foreign_key: 'main_category_id'
  belongs_to :main_category, class_name: 'Category', foreign_key: 'main_category_id'

  validates :name, presence: true

  scope :main_category, -> () { where(main_category_id: nil) }

  after_touch :touch_main, if: :main_category_id


  def all_videos
    return videos unless main_category_id.nil?
    Video.where(category_id: subcategories.pluck(:id).push(id))
  end

  def top_videos
    all_videos.select('videos.id, videos.title, videos.image_preview_url, videos.is_playlist')
    .order('videos.created_at DESC')
    .limit(5)
  end

  def subcategories_videos
    Video.joins(:category).where('categories.main_category_id = ?', self.id)
  end

  def slug
    "#{id}-#{name.parameterize}"
  end

  def touch_main
    main_category.touch
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :category, touch: true

  scope :videos, ->() { where(is_playlist: false) }
  scope :playlists, ->() { where(is_playlist: true) }

  scope :top_10, ->() { order('videos.view DESC').limit(10) }

  validates :url, presence: true

  before_create :check_and_prepare

  def slug
    "#{id}-#{title.parameterize}"
  end

  def check_and_prepare
    begin
      item = is_playlist ? Yt::Playlist.new(id: url) : Yt::Video.new(id: url)
      self.title = item.title
      self.image_preview_url = item.thumbnail_url(:medium)

      if is_playlist
        # TODO : Calculate playlist duration
        # self.duration = item.playlist_items.map(:video).map(:duration).reduce(:+)
        self.first_video_url = item.playlist_items.first.video_id
      else
        self.duration = item.duration
      end

    rescue Yt::Errors::NoItems
      false        
    end
  end

end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < Admin::BaseController

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to admin_artist_path(@artist.id), notice: 'Success!'
    else
      redirect_to admin_dashboard_index_path, alert: 'Un nom est nécessaire'
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def destroy
    @artist = Artist.find(params[:id])
    if @artist.destroy
      redirect_to admin_dashboard_index_path, notice: 'Artist supprimé!'
    else
      redirect_to admin_dashboard_index_path, alert: 'Error'
    end
  end

  private

    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_filter :verify_admin, unless: :devise_controller?

  layout 'admin'

  private

    def verify_admin
      return redirect_to admin_path if not user_signed_in? 
      raise 'Forbidden' unless current_user.is_admin
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_category_path(@category.id), notice: 'Success!'
    else
      redirect_to admin_dashboard_index_path, alert: 'Un nom est nécessaire'
    end
  end

  def show
    @category = Category.find(params[:id])

    @common = @category if params[:common]

    unless @category.main_category.nil?
      @subcategory = @category
      @category = @subcategory.main_category
    end

  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      path = @category.main_category.nil? ? admin_dashboard_index_path : admin_category_path(@category.main_category)
      redirect_to path, notice: 'Category supprimé!'
    else
      redirect_to admin_dashboard_index_path, alert: 'Error'
    end
  end

  private

    def category_params
      params.require(:category).permit(:name, :main_category_id)
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def index
    @category = Category.new
    @artist = Artist.new
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController

  def new
    raise 'Forbidden' if user_signed_in? and not current_user.is_admin
    render layout: 'admin'
  end

  def create
    user = User.where(email: params[:user][:email]).first
    return redirect_to admin_path, alert: "Vous n'avez pas accés à cette partie du site" if user and not user.try(:is_admin)
    super
  end

  def after_sign_in_path_for resource
    admin_dashboard_index_path if request.path.starts_with?('/admin')
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController

  def create
    @video = Video.new(video_params)

    path = get_redirect_path(@video)

    if @video.save
      redirect_to path, notice: 'Success!'
    else
      redirect_to path, alert: 'Video est introuvable'
    end
  end

  def destroy
    @video = Video.find(params[:id])

    path = get_redirect_path(@video)

    if @video.destroy
      redirect_to path, notice: 'Video supprimé!'
    else
      redirect_to path, alert: 'Error'
    end
  end

  private

    def video_params
      params.require(:video).permit(:url, :is_playlist, :category_id)
    end

    def get_redirect_path video
      if video.category.main_category_id.nil?
        path = admin_category_path(id: video.category_id, common: true)
      else
        path = admin_category_path(video.category_id)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    if stale? Category.main_category.order('created_at DESC').first
      categories = Category.main_category.order('created_at DESC').select('id, name, updated_at')

      respond_to do |format|
        format.json { render json: categories, except: :videos_count, root: false }
      end
    end
  end

  def show
    @category = Category.find(params[:id])

    if stale? @category

      @videos = @category.all_videos.order('created_at DESC')

      respond_to do |format|
        format.html { redirect_to "/#/categories/#{@category.slug}" }
        format.json { render json: @videos, except: [:category_slug], meta: { category_name: @category.name, subcategories_names: @category.subcategories.pluck(:name) } }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def home_items

    videos = Video.order('created_at DESC').limit(10)

    respond_to do |format|
      format.json do
        render json: videos,
        meta: {
          top_videos: ActiveModel::ArraySerializer.new(Video.videos.top_10, each_serializer: VideoSerializer),
          top_playlists: ActiveModel::ArraySerializer.new(Video.playlists.top_10, each_serializer: VideoSerializer)
        },
        except: :yt_url
      end
    end
    
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def show
    video = Video.find(params[:id])
    redirect_to "/#/categories/#{video.category.slug}/#{video.slug}"
  end

  def update
    video = Video.find(params[:id])
    video.update_attributes!(video_params)

    respond_to do |format|
      format.json { render json: video, root: false }
    end
  end

  private

    def video_params
      params.require(:video).permit(:view)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/artists/_new.html.haml
#artist-new
  %h2 Add an artist
  = simple_form_for @artist, url: admin_artists_path do |f|
    = f.input :name, required: false
    .form-actions
      = f.button :submit, 'Add'

app/views/admin/artists/show.html.haml
= @artist.name

app/views/admin/categories/_category_show.html.haml
.col-xs-12.col-md-6
  #category-new
    %h2 Add a Subcategory
    = simple_form_for Category.new, url: admin_categories_path do |f|
      = f.input :name, required: false, autofocus: true
      = f.hidden_field :main_category_id, value: @category.id
      .form-actions
        = f.button :submit, 'Add'
  %hr
  %br
  %ul.list-group
    %li.list-group-item
      = link_to 'Common', admin_category_path(id: category.id, common: true )
      %span.badge
        = "Playlists : #{category.videos.playlists.count}"
      %span.badge
        = "Videos : #{category.videos.videos.count}"
         
    - category.subcategories.each do |sub|
      %li.list-group-item
        = link_to sub.name, admin_category_path(sub.id)
        = link_to admin_category_path(sub.id), method: :delete, class: 'pull-right' do
          %span.glyphicon.glyphicon-remove{ style: 'margin-left: 15px; color: hsl(2, 65%, 50%)' }
        %span.badge
          = "Playlists : #{sub.videos.playlists.count}"
        %span.badge
          = "Videos : #{sub.videos.videos.count}"
.col-xs-12.col-md-6
  %h3 Total
  = "Videos: #{category.all_videos.videos.count}"
  = "Playlists: #{category.all_videos.playlists.count}"
  %h3 Last videos
  %ul#list-last-videos
    - category.all_videos.order('created_at DESC').limit(10).each do |video|
      %li
        %span.glyphicon{ class: (video.is_playlist ? 'glyphicon-list' : 'glyphicon-play')}
        = video.title

app/views/admin/categories/_new.html.haml
#category-new
  %h2 Add a category
  = simple_form_for @category, url: admin_categories_path do |f|
    = f.input :name, required: false, autofocus: true
    .form-actions
      = f.button :submit, 'Add'

app/views/admin/categories/_subcategory_show.html.haml
.col-xs-12.col-md-6
  #week-video-new
    %h2 Add a video
    = simple_form_for Video.new, url: admin_videos_path do |f|
      = f.input :url, label: 'key', required: false, autofocus: true
      = f.input :category_id, as: :hidden, input_html: { value: category.id }
      .form-actions
        = f.button :submit, 'Add'
  %hr
  - if category.videos.videos.count.zero?
    = 'No videos'
  - category.videos.videos.each do |video|
    .media.col-xs-12
      = link_to '#', class: 'pull-left' do
        = image_tag video.image_preview_url, width: '120'
      .media-body
        %h4.media-heading
          = video.title
          = link_to admin_video_path(video.id), method: :delete do
            %span.glyphicon.glyphicon-remove{ style: 'color: hsl(2, 65%, 50%)' }
        Created : 
        = video.created_at.to_formatted_s(:long_ordinal)
.col-xs-12.col-md-6
  #playlist-new
    %h2 Add a playlist
    = simple_form_for Video.new, url: admin_videos_path do |f|
      = f.input :url, label: 'key', required: false
      = f.input :category_id, as: :hidden, input_html: { value: category.id }
      = f.input :is_playlist, as: :hidden, input_html: { value: true }
      .form-actions
        = f.button :submit, 'Add'
  %hr
  - if category.videos.playlists.count.zero?
    = 'No playlist'
  - category.videos.playlists.order('updated_at DESC').each do |playlist|
    .media.col-xs-12
      = link_to '#', class: 'pull-left' do
        = image_tag playlist.image_preview_url, width: '120'
      .media-body
        %h4.media-heading
          = playlist.title
          = link_to admin_video_path(playlist.id), method: :delete do
            %span.glyphicon.glyphicon-remove{ style: 'color: hsl(2, 65%, 50%)' }
        %br
        Created : 
        = playlist.created_at.to_formatted_s(:long_ordinal)

app/views/admin/categories/show.html.haml
.jumbotron
  %h1
    = link_to @category.name, admin_category_path(@category)
    - if @subcategory
      = " - #{@subcategory.name}"
    - if @common
      = '- Common'
.row
  - if @subcategory or @common
    = render 'admin/categories/subcategory_show', category: (@subcategory || @common), videos: @videos, playlists: @playlists
  - else
    = render 'admin/categories/category_show', category: @category

app/views/admin/dashboard/index.html.haml
.row
  .col-xs-6
    = render 'admin/categories/new'
    %hr
    %ul.list-group
      - Category.main_category.each do |category|
        %li.list-group-item
          = link_to category.name, admin_category_path(category.id)
          = link_to admin_category_path(category.id), method: :delete, class: 'pull-right' do
            %span.glyphicon.glyphicon-remove{ style: 'margin-left: 15px; color: hsl(2, 65%, 50%)' }
          %span.badge
            = "Subcategories : #{category.subcategories.count}"
  .col-xs-6
    = render 'admin/artists/new'
    %hr
    %ul.list-group
      - Artist.all.each do |artist|
        %li.list-group-item
          = link_to artist.name, admin_artist_path(artist.id)
          %br
          = link_to 'X', admin_artist_path(artist.id), method: :delete

app/views/layouts/admin.html.haml
!!!5
%html
  %head
    %title Dweet
    = stylesheet_link_tag 'admin/admin', media: 'all'
    = csrf_meta_tags
  %body#admin
    %nav.navbar.navbar-default{:role => "navigation"}
      .container-fluid
        .navbar-header
          = link_to 'Dweet', admin_dashboard_index_path, class: 'navbar-brand'
        - if current_user and current_user.is_admin
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav.navbar-left
              %li{ class: ('active' if current_page?(admin_dashboard_index_path))}
                = link_to 'Dashboard', admin_dashboard_index_path
              - Category.main_category.each do |main|
                %li{ class: ('active' if current_page?(admin_category_path(main)))}
                  = link_to main.name, admin_category_path(main)

            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to 'Deconnexion', destroy_user_session_path, method: :delete


    .container
      - flash.each do |k, v|
        - cl = k == 'notice' ? 'alert-success' : 'alert-danger'
        %p{ class: "alert #{cl} "}= v
      = yield

    = javascript_include_tag 'application'

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Mek We Dweet TV - Bass Music Pon de Internet
    %base{ href: '/' }
    %meta{ name: 'viewport', content:'width=device-width, initial-scale=1' }
    %meta{ name: 'description', content:'Web TV for the Bass Music !' }
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body{ data: { 'ng-app' => 'Dweet'} }
    #header.col-md-12
      #banner
        #logo
    #main-menu.col-md-12{ data: { 'ng-controller' => 'MenuCtrl' } }
      %div{ data: { 'ng-cloak' => '', 'preload-category' => '', 'categories' => ActiveModel::ArraySerializer.new(Category.main_category.order('created_at DESC'), each_serializer: CategorySerializer).to_json } }
      %ul.nav.nav-pills.nav-justified
        %li{ data: { 'ng-click' => 'setActivePage(0)', 'ng-class' => '{active: activeCategoryId == 0}' } }
          = link_to root_path do
            %span.glyphicon.glyphicon-home
        %li{ data: { 'ng-repeat' => 'category in categories track by $index', 'ng-click' => 'setActivePage(category.id)', 'ng-class' => '{active: category.id == activeCategoryId}' } }
          %a{ data: { 'ng-href' => 'categories/{{category.slug}}' }}
            {{category.name}}
    #view{ data: { 'ng-view' => '' } }

    = javascript_include_tag 'application', defer: true
    %link{ rel:'stylesheet', type:'text/css', href:'//cdn.jsdelivr.net/jquery.slick/1.3.14/slick.css' }
    %script
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-58438014-1', 'auto');
      ga('send', 'pageview');